export class ExPalletModel {
    public PALLET_ID: string;
    public PALLET_DATE: string;
    public PLANT: string;
    public ZONE1: string;
    public GROSS_W: number;
    public NET_W: number;
    public UNIT_W: string;
    public MATERIAL: string;
    public SALES_ORD: string;
    public PALLET_NO: string;
    public TO_SLOC: string;
    public MAKTX: string;
    public MTART: string;
    public GROES: string;
    public POST_IND: string;
    public MAT_DOC: string;
    public MAT_YEAR: string;
    public CHUSR: string;
    public CHDATE: string;
    public CHTIME: string;
    public KUNNR: string;
    public FULLN: string;
    public W_MAT: string;
    public W_SO: string;
    public W_PP: string;
    public C_UNIT: string;
    public POSNR: string;
}